spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    
rest:
  max-conn-total: 500 # connection pool
  max-conn-per-route: 500 # IP,Port 하나 당 연결 제한 갯수
  connect-timeout: 600 # second (초)
  read-timeout: 600 # second (초)

server:
  tomcat:
    max-connections: 500
    max-threads: 400
    min-spare-threads: 300
    accept-count: 100
  servlet:
    session:
      timeout: 2592000 # 30일
  connection-timeout: 180000
 
logging:
  level:
    com.poc.frontend: error
