nodeSelector: 
  role: dev-ops
replicaCount: 1
admissionWebhooks:
  autoGenerateCert:
    enabled: true
  certManager:
    enabled: false

manager:
  collectorImage:
    repository: "otel/opentelemetry-collector-k8s"
  serviceMonitor:
    enabled: true
    extraLabels:
      release: kube-prometheus-stack