apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry-operator 
spec:
  # autoscaler:
  #   minReplicas: 1
  #   maxReplicas: 1
  # targetAllocator:
  #   enabled: true
  #   prometheusCR:
  #     enabled: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      otlp: 
        endpoint: tempo-distributed-distributor.tempo.svc:4317
        tls: 
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
# mode: deployment
# config:
#   exporters:
#     otlp:
#       endpoint: tempo-distributed-distributor.tempo.svc:4317
#       tls:
#         insecure: true
#   service:
#     pipelines:
#       traces:
#         exporters:
#         - logging
#         - otlp
# nodeSelector:
#   role: telemetry