spring:
  cloud:
    config:
      server:
        git:
          uri: http://bitbucket.poc.co.kr/poc_config.git
          basedir: target/config
          default-label: develop
          searchPaths: '**/*'
          username: user
          password: user
          repos:
            local:
              pattern: local*
              uri: file:/home/ec2-user/poc_config
