controller: 
  nodeSelector: 
    role: dev-ops
  ingress: 
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingressClassName: nginx
    hostName: 'jenkins.도메인.kr'