nameOverride: ""
global:
  nodeSelector:
    role: dev-ops
  domain: 'stgargocd.도메인.kr'
configs:
  params:
    server.insecure: true
server:
  name: server
  replicas: 1
  service:
    type: NodePort
  nodeSelector:
    role: dev-ops
repoServer:
  replicas: 1
  nodeSelector:
    role: dev-ops