
version: '3'
services:

  database:
    image: oracle/database
    container_name: oracle/database:21.3.0-ee
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
      - 2484:2484

  # oracle-xe:
  #   image: wnameless/oracle-xe-11g
  #   ports:
  #     - "1521:1521"
  #   environment:
  #     - ORACLE_ALLOW_REMOTE=true
  #   volumes:
  #     - "./oradata:/u01/app/oracle/data"

#   oracle:
#       image: sami12rom/oracle_database19c:19.3.0-ee
#       container_name: oracle
#       ports:
#         - 1521:1521
#         - 5500:5500
#         - 2484:2484
#       environment:
#         - ORACLE_SID=ORCLCDB
#         - ORACLE_PDB=ORCLPDB1
#         - ORACLE_PWD=Oracle123
#         - ORACLE_CHARACTERSET=AL32UTF8
#         - ENABLE_ARCHIVELOG=true
#         - ENABLE_TCPS=true
#       volumes:
#         - ./oradata:/opt/oracle/oradata
#       ulimits:
#         nofile:
#           soft: 1024
#           hard: 65535
#         nproc:
#           soft: 2047
#           hard: 16384
#         stack:
#           soft: 10485760
#           hard: 33554432
#         memlock: 3221225472

# volumes:
#   oracle_data:


