version: '3.9'
services:

  # main 데이터베이스
  postgresql-main:
    container_name: postgresql-main
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./init/pg.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # standby  데이터베이스
  postgesql-standby:
    container_name: postgresql-standby
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./init/pg.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin-client:
    image: dpage/pgadmin4:4.18
    container_name: PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
