
server:
  tomcat:
    max-connections: 500
    max-threads: 400
    min-spare-threads: 300
    accept-count: 100
 
logging:
  level:
    root: info
    com.poc: info
  pattern:
    console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %-30.-30F : %msg%n'
  response:
    length: 50

spring:
  
  redis:
    store-type: redis
    host: 
    port: 6379
    timeout: 300s
    cluster:
      nodes:
        - a
        - b

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-statement-timeout: 65000
    map-underscore-to-camel-case: true
---    
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
---  
logging:
  level:
    root: info
    com.poc.api: debug
    com.zaxxer.hikari: debug
    com.zaxxer.hikari.pool.HikariPool: TRACE
    org:
      springframework:
        transaction:
          interceptor: trace
  #pattern:
    #console: '%d{yyyy-dd-MM HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %-30.-30F : %msg%n' 
  response:
    length: 50
