initChownData:
  enabled: false
persistence:
  enabled: true
adminUser: admin
adminPassword: "도메인"
nodeSelector:
  role: dev-ops
grafana.ini:
  feature_toggles:
    enable: tempoSearch tempoBackendSearch tempoServiceGraph
  # server:
  #   root_url: https://grafana.gosuper.kr

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  ingressClassName: nginx
  hosts: 
    - 'stggrafana.도메인.kr'
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack